package com.redex.hms.forms;

import javax.servlet.http.HttpServletRequest;

import com.redex.hms.configs.core.Injector;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ChameleonTheme;

public class Class4 extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label lblHeading;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */


	public Class4(final HttpServletRequest httpServletRequest) {
		Injector.inject(this, httpServletRequest);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		initForm();

		// TODO add user code here
	}

	private void initForm() {
		lblHeading.setStyleName(ChameleonTheme.LABEL_H4);


	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("60.0%");
		setHeight("60.0%");

		// lblHeading
		lblHeading = new Label();
		lblHeading.setImmediate(false);
		lblHeading.setWidth("-1px");
		lblHeading.setHeight("-1px");
		lblHeading.setValue("This is class 4");
		mainLayout.addComponent(lblHeading);

		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1);

		return mainLayout;
	}

	@Override
	public void enter(final ViewChangeEvent event) {
		// TODO Auto-generated method stub

	}

}
