package com.redex.hms.forms;

import javax.servlet.http.HttpServletRequest;

import com.redex.hms.configs.core.Injector;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class MyDesignClass extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblName;
	@AutoGenerated
	private TextField textField_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MyDesignClass(final HttpServletRequest httpServletRequest) {
		Injector.inject(this, httpServletRequest);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// TODO add user code here
	}



	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("400px");
		mainLayout.setHeight("200px");

		// top-level component properties
		setWidth("400px");
		setHeight("200px");

		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:80.0px;left:143.0px;");

		// lblName
		lblName = new Label();
		lblName.setImmediate(false);
		lblName.setWidth("-1px");
		lblName.setHeight("-1px");
		lblName.setValue("Label in New");
		mainLayout.addComponent(lblName, "top:80.0px;left:10.0px;");

		return mainLayout;
	}



	@Override
	public void enter(final ViewChangeEvent event) {
		// TODO Auto-generated method stub

	}

}
